
import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";

// Configuration de la police Rubik avec les sous-ensembles et styles nécessaires
const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
  // Vous pouvez ajouter d'autres options comme :
  // weight: ["400", "500", "700"], // Pour charger plusieurs poids
  // style: ["normal", "italic"],   // Pour charger les italiques
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}